export const data = {
  schedule: {
    Fall2025: {
      courses: [
        
        {
          blockColor: "#81D4FA",
          crn: 37664,
          code: "CMPT2363",
          section: "001",
          title: "UI Design",
          instructor: "Janzen, Izabelle",
          message: "Registered",
          credits: 3,
          level: "Undergraduate",
          scheduleType: "Lecture",
          courseEnrollment: {
            capacity: 30,
            current: 25,
            waitlistMax: 100,
            waitlistCurrent: 0,
          },
          days: ["Tuesday", "Wednesday"],
          dateRange: {
            startDate: "2025-09-01",
            endDate: "2025-12-10",
          },
          time: {
            startTime: "08:30",
            endTime: "10:20",
            hours: 1.83,
          },
          location: {
            roomNum: "N661",
            campus: "New Westminister Campus",
            campusShort: "NWN",
            building: "South East Building Westminister - North Bldg",
          },
          links: {
            blackboard: "#",
            courseInfo: "https://www.douglascollege.ca/course/cmpt-2363",
          },
          description:
            "This is a project-based course providing a comprehensive introduction to user interface (UI) design. Topics include goals and history of UI design, human-computer interactions and user experience, social impact of UI, and the UI design process. Students will incorporate major aspects of user interface design, including user research, user interface patterns, prototyping, and evaluation, into a group project that provides them with hands-on experience of UI design disciplines.",
        },
        {
          blockColor: "#ff867c",
          crn: 37841,
          code: "CMPT2276",
          section: "002",
          title: "Intro to Software Engineering",
          instructor: "Janzen, Izabelle",
          message: "Waitlisted",
          credits: 3,
          level: "Undergraduate",
          scheduleType: "Lecture",
          courseEnrollment: {
            capacity: 30,
            current: 30,
            waitlistMax: 100,
            waitlistCurrent: 2,
          },
          days: ["Monday", "Thursday"],
          dateRange: {
            startDate: "2025-09-01",
            endDate: "2025-12-10",
          },
          time: {
            startTime: "08:30",
            endTime: "10:20",
            hours: 1.83,
          },
          location: {
            roomNum: "N661",
            campus: "New Westminister Campus",
            campusShort: "NWN",
            building: "South East Building Westminister - North Bldg",
          },
          links: {
            blackboard: "#",
            courseInfo: "https://www.douglascollege.ca/course/cmpt-2276",
          },
          description: "This course provides an overview of standard paradigms and engineering practices as applied to software development. Topics include major phases incorporated in Systems Development Life Cycle (SDLC), software project management issues, and software development core activities from planning to implementation and deployment. Students will participate in a team project that employs an iterative development process and utilizes modern tools that are vital to the success of software development projects to construct a software solution to a real-world case study.",
        },
        {
          blockColor: "#7cff8dff",
          crn: 12240,
          code: "ENGL1114",
          section: "016",
          title: "Reading Poetry",
          instructor: "Trainor, Kim",
          message: "Registered",
          credits: 3,
          level: "Undergraduate",
          scheduleType: "Lecture",
          courseEnrollment: {
            capacity: 30,
            current: 21,
            waitlistMax: 100,
            waitlistCurrent: 0,
          },
          days: ["Wednesday", "Friday"],
          dateRange: {
            startDate: "2025-09-01",
            endDate: "2025-12-10",
          },
          time: {
            startTime: "10:30",
            endTime: "12:20",
            hours: 1.83,
          },
          location: {
            roomNum: "S3312",
            campus: "New Westminister Campus",
            campusShort: "NWS",
            building: "South East Building Westminister - South Bldg",
          },
          links: {
            blackboard: "#",
            courseInfo: "https://www.douglascollege.ca/course/engl-1114",
          },
          description: "In this course students will learn to closely read, interpret and write about poetry. The poems assigned will be various in nature and will cover a range of poets and poetic forms.",
        },
        
      ],
    },
    Winter2026: {
      courses: [
        {
          blockColor: "#81D4FA",
          crn: 37664,
          code: "CMPT2363",
          section: "001",
          title: "UI Design",
          instructor: "Janzen, Izabelle",
          message: "Registered",
          credits: 3,
          level: "Undergraduate",
          scheduleType: "Lecture",
          courseEnrollment: {
            capacity: 30,
            current: 25,
            waitlistMax: 100,
            waitlistCurrent: 0,
          },
          days: ["Tuesday", "Thursday"],
          dateRange: {
            startDate: "2026-01-01",
            endDate: "2026-05-10",
          },
          time: {
            startTime: "12:30",
            endTime: "14:20",
            hours: 1.83,
          },
          location: {
            roomNum: "N661",
            campus: "New Westminister Campus",
            campusShort: "NWN",
            building: "South East Building Westminister - North Bldg",
          },
          links: {
            blackboard: "#",
            courseInfo: "https://www.douglascollege.ca/course/cmpt-2363",
          },
          description:
            "This is a project-based course providing a comprehensive introduction to user interface (UI) design. Topics include goals and history of UI design, human-computer interactions and user experience, social impact of UI, and the UI design process. Students will incorporate major aspects of user interface design, including user research, user interface patterns, prototyping, and evaluation, into a group project that provides them with hands-on experience of UI design disciplines.",
        },
        
        {
          blockColor: "#ff867c",
          crn: 37840,
          code: "CMPT2276",
          section: "003",
          title: "Intro to Software Engineering",
          instructor: "Janzen, Izabelle",
          message: "Registered",
          credits: 3,
          level: "Undergraduate",
          scheduleType: "Lecture",
          courseEnrollment: {
            capacity: 30,
            current: 30,
            waitlistMax: 100,
            waitlistCurrent: 2,
          },
          days: ["Monday", "Thursday"],
          dateRange: {
            startDate: "2026-01-01",
            endDate: "2026-05-10",
          },
          time: {
            startTime: "08:30",
            endTime: "10:20",
            hours: 1.83,
          },
          location: {
            roomNum: "N661",
            campus: "New Westminister Campus",
            campusShort: "NWN",
            building: "South East Building Westminister - North Bldg",
          },
          links: {
            blackboard: "#",
            courseInfo: "https://www.douglascollege.ca/course/cmpt-2276",
          },
          description: "This course provides an overview of standard paradigms and engineering practices as applied to software development. Topics include major phases incorporated in Systems Development Life Cycle (SDLC), software project management issues, and software development core activities from planning to implementation and deployment. Students will participate in a team project that employs an iterative development process and utilizes modern tools that are vital to the success of software development projects to construct a software solution to a real-world case study.",
        },
        {
          blockColor: "#7cff8dff",
          crn: 37841,
          code: "ENGL1114",
          section: "001",
          title: "Reading Poetry",
          instructor: "Trainor, Kim",
          message: "Registered",
          credits: 3,
          level: "Undergraduate",
          scheduleType: "Lecture",
          courseEnrollment: {
            capacity: 30,
            current: 21,
            waitlistMax: 100,
            waitlistCurrent: 0,
          },
          days: ["Wednesday", "Friday"],
          dateRange: {
            startDate: "2026-01-01",
            endDate: "2026-05-10",
          },
          time: {
            startTime: "10:30",
            endTime: "12:20",
            hours: 1.83,
          },
          location: {
            roomNum: "S3312",
            campus: "New Westminister Campus",
            campusShort: "NWS",
            building: "South East Building Westminister - South Bldg",
          },
          links: {
            blackboard: "#",
            courseInfo: "https://www.douglascollege.ca/course/engl-1114",
          },
          description: "In this course students will learn to closely read, interpret and write about poetry. The poems assigned will be various in nature and will cover a range of poets and poetic forms.",
        },
        {
          blockColor: "#ff7ce9ff",
          crn: 15066,
          code: "CMPT",
          section: "001",
          title: "Designing with Raspberry Pi",
          instructor: "Link, Li",
          message: "Registered",
          credits: 3,
          level: "Undergraduate",
          scheduleType: "Lecture",
          courseEnrollment: {
            capacity: 30,
            current: 21,
            waitlistMax: 100,
            waitlistCurrent: 0,
          },
          days: ["Monday", "Wednesday"],
          dateRange: {
            startDate: "2026-01-01",
            endDate: "2026-05-10",
          },
          time: {
            startTime: "14:30",
            endTime: "16:20",
            hours: 1.83,
          },
          location: {
            roomNum: "S0620",
            campus: "New Westminister Campus",
            campusShort: "NWS",
            building: "South East Building Westminister - South Bldg",
          },
          links: {
            blackboard: "#",
            courseInfo: "https://www.douglascollege.ca/course/cmpt-2200",
          },
          description: "This course provides the student with the necessary knowledge of the Raspberry Pi to design and develop practical applications. Initial emphasis will be placed on the embedded Linux OS, configuring, setting up and programming the Pi. In the latter part of the course, students will be able to apply that knowledge to case studies and projects.",
        },
      ],
    },
  },
  totalHours: {},
};
